---
title: "practice"
format: html
server: shiny
---


## R Shiny
```{r}
library(shiny)
ui <- fluidPage(
  #application title
  titlePanel("Investigation of Mammal Sleep Data"),
  #Sidebar with options for the data set 
  sidebarLayout(
    sidebarPanel(
      h3("Select the mammals biological order: "),
      selectizeInput("vore",
                     "Vore",
                     selected = "omni",
                     choices = levels(as.factor(msleep$vore))
      ),
      #Show outputs 
      mainPanel(
        plotOutput("sleepPlot"),
        textOutput("info"),
        tableOutput("table")
      )
    )
  )
)
```


```{r}
server <- -function(input, output, session) {
  #get data for only order specified 
  getData <- reactive({
    vores <- input$vore
    msleep %>% filter(vore == vores)
  })
  #create plot 
  output$sleepPlot <- renderPlot({
    #get data 
    sleepData <- getData()
    #base plotting object
    g <- ggplot(sleepData, aes(x = bodywt, y = sleep_total))
    if (input$conservation) {
      g + geom_point(size = input$size, aes(col = conservation))
    } else {
    g + geom_point(size = input$size)
  }
})
...
```

